pipeline {
    agent any

    environment {
        SONAR_HOST = 'http://host.docker.internal:9000'
        SONAR_TOKEN = 'squ_5240fd71d8cded487d015209794e146bc1a1cc12'
        DOCKER_IMAGE = 'thiagobarlanza/taskmaster-pro'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'cd taskmaster-pro && ./mvnw clean compile'
            }
        }

        stage('Test & Coverage') {
            steps {
                sh 'cd taskmaster-pro && ./mvnw test jacoco:report'
            }
            post {
                always {
                    junit 'taskmaster-pro/target/surefire-reports/*.xml'
                    publishHTML([
                        reportDir: 'taskmaster-pro/target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                    ])
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'cd taskmaster-pro && ./mvnw sonar:sonar -Dsonar.host.url=${SONAR_HOST} -Dsonar.login=${SONAR_TOKEN}'
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Package') {
            steps {
                sh 'cd taskmaster-pro && ./mvnw package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('taskmaster-pro') {
                        docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', 'docker-hub-credentials') {
                        docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}").push()
                        docker.image("${DOCKER_IMAGE}:latest").push()
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs for details.'
        }
    }
}
