pipeline {

    agent any

    environment {
        SONAR_HOST = 'http://host.docker.internal:9000'
        SONAR_TOKEN = 'squ_XXXX'
        DOCKER_IMAGE = 'thiagobarlanza/taskmaster-pro'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('taskmaster-pro') {
                    sh './mvnw clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('taskmaster-pro') {
                    sh './mvnw test'
                }
            }
            post {
                always {
                    junit 'taskmaster-pro/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir('taskmaster-pro') {
                        sh """
                            ./mvnw sonar:sonar \
                            -Dsonar.host.url=$SONAR_HOST \
                            -Dsonar.login=$SONAR_TOKEN
                        """
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('taskmaster-pro') {
                    sh './mvnw package -DskipTests'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}